from django.contrib import admin
from django.urls import path,include
from home import views

urlpatterns = [
    path('', views.index, name="home"),
    path('indexforCustomer', views.indexforCustomer, name="homeforcustomer"),
    path('<str:IPOid>/<str:OrderType>/update_pann/<str:GrpName>/<str:OrderCategory>/<str:InvestorType>', views.Update_pann,name = "OrderDetail_update"),
    path('clear-selected-records/', views.ClearSelectedRecords, name='clear_selected_records'),
    path('ChangePassword', views.ChangePassword, name="ChangePassword"),
    path('get-options/', views.get_options, name='get_options'),
    path('<str:IPOid>/get-rates/<str:Ordtyp>', views.get_rates_json, name='get_rates_json'),
    path('<str:IPOid>/<str:OrderType>/IPO_Allotment/<str:group>/<str:IPOType>/<str:InvestType>', views.IPO_Allotment),
    path('<str:IPOid>/<str:OrderType>/IPO_Allotment/<str:group>/<str:IPOType>/<str:InvestType>/<str:Rate>', views.IPO_Allotment, name='get_options'),
    path('get_pancards/<str:IPOid>/<str:OrderType>/<str:group>/<str:IPOType>/<str:InvestType>', views.get_pancards),
    path('get_pancards/<str:IPOid>/<str:OrderType>/<str:group>/<str:IPOType>/<str:InvestType>/<str:Rate>', views.get_pancards, name='get_pancards'),
    path('ChangeUserpassword', views.Changepassword, name="ChangeUserpassword"),
    path('IPOSETUP', views.IPOSETUP, name="IPOSETUP"),
    path('ClientSetup', views.ClientSetup, name="ClientSetup"),
    path('ClientSetup/<str:PanNoId>', views.ClientSetup, name="ClientSetup"),
    path('GroupSetup', views.GroupSetup, name="GroupSetup"),
    path('AddIPO', views.AddIPO, name="AddIPO"),
    path('AddClient', views.AddClient, name="AddClient"),
    path('AddGroup', views.AddGroup, name="AddGroup"),
    path('ErrorCSV', views.Error_csv, name="ErrorCSV"),
    path('AddGroup/<str:IPOid>/<str:Action>', views.AddGroupFromPlaceOrder,name="AddGroupFromPlaceOrder"),
    #Bulk Group ADD
    path('BulkUploadGroup', views.BulkUploadGroup, name="BulkUploadGroup"),
    path('DownloadGroupSample', views.DownloadGroupSample, name="DownloadGroupSample"),
    path('edit/<str:IPOid>', views.edit),
    path('EditClient/<str:PanNoId>', views.EditClient),
    path('EditGroup/<str:GroupNameId>', views.EditGroup),
    path('update/<str:IPOid>', views.update),
    path('<str:IPOid>/updatepreopenprice/<str:group>/<str:IPOType>/<str:InvestType>', views.updatepreopenprice),
    path('<str:IPOid>/<str:OrderDetailId>/EditOrderPreOpenPrice/<str:OrderCategory>/<str:InvestorType>/<str:group>/<str:IPOType>/<str:InvestType>', views.EditOrderPreOpenPrice),
    path('UpdateClient/<str:PANNoId>', views.UpdateClient),
    path('UpdateGroup/<str:GroupNameId>', views.UpdateGroup),
    path('delete/<int:IPOid>', views.destroy, name='destroy'),
    path('DeleteClient/<str:PANNoId>', views.DeleteClient),
    path('DeleteAllClient', views.DeleteAllClient),
    path('DeleteGroup/<str:GroupNameId>', views.DeleteGroup),
    path('DeleteOrder/<str:IPOid>/<str:OrderId>/<str:GrpName>/<str:OrderCategory>/<str:InvestorType>', views.DeleteOrder),
    path('<str:IPOid>/SetRate', views.SetRate),
    path('<str:IPOid>/BUY', views.BUY),
    path('BUY/<str:IPOid>/<str:selectgroup>', views.BUY),
    path('<str:IPOid>/SELL', views.sell),
    path('SELL/<str:IPOid>/<str:selectgroup>', views.sell),
    path('<str:IPOid>/Order', views.OrderFunction),
    path('<str:IPOid>/EditOrder/<str:OrderId>/<str:Grpf>/<str:OrCtf>/<str:InTyf>', views.EditOrder),
    path('<str:IPOid>/<str:OrderId>/UpdateOrder/<str:Grpf>/<str:OrCtf>/<str:InTyf>', views.UpdateOrder),
    path('trades/update_order/<str:OrderId>', views.GlobalUpdateOrder, name='global_update_order'),
    path('<str:IPOid>/<str:OrderId>/EditOrderRate/<str:GrpName>/<str:OrderCategory>/<str:InvestorType>', views.EditOrderRate),
    path('<str:IPOid>/OrderDetail/<str:Ordtyp>', views.OrderDetailFunction),
    path('<str:IPOid>/OrderDetail/<str:Ordtyp>/<str:GrpName>/<str:OrderCategory>/<str:InvestorType>', views.OrderDetailFunction),
    path('<str:IPOid>/OrderDetail/<str:Ordtyp>/<str:GrpName>/<str:OrderCategory>/<str:InvestorType>/<str:OrderDate>/<str:OrderTime>', views.OrderDetailFunction),
    path('<str:IPOid>/OrderDetail/<str:Ordtyp>/<str:GrpName>/<str:OrderCategory>/<str:InvestorType>/<str:OrderDate>/<str:OrderTime>/<str:Rate>', views.OrderDetailFunction),
    path('<str:IPOid>/Order/<str:Groupfilter>/<str:OrderCategoryFilter>/<str:InvestorTypeFilter>',views.filterfromstatus),
    path('<str:IPOid>/<str:OrderType>/AddPan-<str:OrderDetailId>/<str:GrpName>/<str:OrderCategory>/<str:InvestorType>/<str:OrderDate>/<str:OrderTime>',views.AddPan, name="AddPan"),
    path('<str:IPOid>/<str:OrderType>/FirmAllotment/<str:GrpName>/<str:OrderCategory>/<str:InvestorType>',views.FirmAllotment),
	path('<str:IPOid>/<str:OrderType>/FirmAllotment/<str:GrpName>/<str:OrderCategory>/<str:InvestorType>/<str:Rate>',views.FirmAllotment, name='FirmAllotment'),
    path('autocomplete', views.autocomplete, name='autocomplete'),
    path('autocomplete1', views.autocomplete1, name='autocomplete1'),
    path('<str:IPOid>/Billing', views.Billing, name='Billing'),
    path('<str:IPOid>/Billing/<str:group>/<str:IPOType>/<str:InvestType>', views.FileterBilling),
    path('<str:IPOid>/Billing/<str:group>/<str:IPOType>/<str:InvestType>/<str:Rate>', views.FileterBilling, name='Billing'),
    path('<str:IPOid>/download-Billing/<str:group>/<str:IPOType>/<str:InvestorType>',views.exportBillingFilter, name='exportBillingFilter'),
    path('download-Groupwise',views.exportGroupwise, name='exportBillingFilter'),
    path('<str:IPOid>/Sample-Order',views.Sample_Order, name='Sample-Order'),
    path('<str:IPOid>/download-Billing-Pdf/<str:group>/<str:IPOType>/<str:InvestorType>',views.exportBillingFilterpdf, name='exportBillingFilterpdf'),
    path('<str:IPOid>/Backup/',views.Backup, name='Backup'),
    path('AllIpoBackup',views.AllIpoBackup, name='AllIpoBackup'),
    path('<str:IPOid>/download-csv/<str:OrderType>/<str:group>/<str:IPOType>/<str:InvestorType>/<str:OrderDate>/<str:OrderTime>',views.export),
    path('<str:IPOid>/download-csv/<str:OrderType>/<str:group>/<str:IPOType>/<str:InvestorType>/<str:OrderDate>/<str:OrderTime>/<str:Rate>',views.export, name='OrderDetail_download'),
    path('<str:IPOid>/Group_wise-download-csv/<str:OrderType>/<str:IPOType>/<str:InvestorType>/<str:OrderDate>/<str:OrderTime>', views.Group_wise_export),
    path('<str:IPOid>/Group_wise-download-csv/<str:OrderType>/<str:IPOType>/<str:InvestorType>/<str:OrderDate>/<str:OrderTime>/<str:Rate>', views.Group_wise_export, name='OrderDetail_download'),
    path('<str:IPOid>/Dashboard/<str:value>',views.dashboard, name='Dashboard'),
    path('<str:IPOid>/DashboardForm/<str:value>',views.dashboardform, name='DashboardForm'),
    path('<str:IPOid>/download-AllRecords-csv/<str:OrderType>/<str:group>/<str:IPOType>/<str:InvestorType>/<str:OrderDate>/<str:OrderTime>',views.exportall),
    path('<str:IPOid>/download-AllRecords-csv/<str:OrderType>/<str:group>/<str:IPOType>/<str:InvestorType>/<str:OrderDate>/<str:OrderTime>/<str:Rate>',views.exportall, name='OrderDetail_download_AllRecords'),
    path('<str:IPOid>/Group_wise-download-AllRecords-csv/<str:OrderType>/<str:IPOType>/<str:InvestorType>/<str:OrderDate>/<str:OrderTime>', views.Group_wise_exportall),
    path('<str:IPOid>/Group_wise-download-AllRecords-csv/<str:OrderType>/<str:IPOType>/<str:InvestorType>/<str:OrderDate>/<str:OrderTime>/<str:Rate>', views.Group_wise_exportall, name='OrderDetail_download_AllRecords'),
    path('<str:IPOid>/Status', views.Status, name='Status'),
    path('update-telly-status/', views.update_telly_status, name='update_telly_status'),
    path('GroupWiseDashboard',views.GroupWiseDashboard, name='GroupWiseDashboard'),
    path('group-billing-details/', views.group_billing_details, name='group_billing_details'),
    path('group-billing-details/<int:group_id>/', views.group_billing_details, name='group_billing_details_by_id'),
    path('trades', views.trades_page, name='trades'),
    path('trades/Sample-Order', views.Sample_Order, name='Trades-Sample-Order'),
    path('trades/upload-csv', views.Order_upload, name='Trades-Order-upload'),

    path('BackUp',views.BackUp, name='BackUp'),
    path('<str:IPOid>/<str:OrderType>/upload-csv/<str:GrpName>/<str:OrderCategory>/<str:InvestorType>/<str:OrderDate>/<str:OrderTime>',views.OrderDetail_upload, name="OrderDetail_upload"),
    path('<str:IPOid>/<str:OrderType>/upload-csv/<str:GrpName>/<str:OrderCategory>/<str:InvestorType>/<str:OrderDate>/<str:OrderTime>/<str:Rate>',views.OrderDetail_upload, name="OrderDetail_upload"),
    path('<str:IPOid>/upload-csv/<str:Groupfilter>/<str:Ordercatagoryfilter>/<str:InvestorTypefilter>',views.Order_upload, name="Order_upload"),
    path('AddPayment', views.AddPayment, name="AddPayment"),
    path('login', views.loginUser, name="login"),
    path('logout', views.logoutUser, name="logout"),
    path('<str:IPOid>/ShareBill',views.GroupBillShare ,name='GroupWiseBillShare'),
    path("accounting/", views.accounting_view, name="accounting"),
    path("get-accounting-entries/", views.get_accounting_entries, name="get_accounting_entries"),
    path("save_transaction/", views.save_transaction, name="save_transaction"),
    path("save_transaction_group/", views.save_transaction_group, name="save_transaction_group"),
    path("update-accounting/", views.update_accounting, name="update_accounting"),
    path("bulk-delete-accounting/", views.bulk_delete_accounting, name="bulk_delete_accounting"),
    path("soft-delete-accounting/<int:entry_id>/", views.soft_delete_accounting, name="soft_delete_accounting"),
    path("restore-accounting/<int:entry_id>/", views.restore_accounting, name="restore_accounting"),
    path("add-transaction/", views.add_transaction, name="add_transaction"),
    path("add_transaction_group/", views.add_transaction_group, name="add_transaction_group"),
    path("accounting-logs/", views.accounting_logs_view, name="accounting_logs"),
    # path('download-Accounting',views.exportAccountiong, name='exportAccountingFilter'),
    path("ipo_transaction/", views.ipo_transaction, name="ipo_transaction"),
    path("ipo_transaction1 /", views.ipo_transaction1, name="ipo_transaction1"),
    path('AccountingBackup/', views.AccountingBackup, name='AccountingBackup'),
    path('share-records/',views.Share_AppDetails ,name='Share_AppDetails'),
    path('user-profile/', views.user_profile, name='user_profile'),
    path('update-user-profile/', views.update_user_profile, name='update_user_profile'),
    path("send-telegram-otp/", views.send_telegram_otp, name="send_telegram_otp"),
    path('verify-telegram-otp/', views.verify_telegram_otp, name='verify_telegram_otp'),
    path("place-order/<int:IPOid>/<str:order_type>/",views.place_order_view, name="place_order"),
    path('share-status-telegram/', views.share_status_telegram, name='share_status_telegram'),
    path('<str:IPOid>/send-status-telegram/', views.send_status_to_telegram, name='send_status_to_telegram'),
    path('<int:IPOid>/DeleteAllOrders/', views.DeleteAllOrders, name='delete_all_orders'),
    path("bulk_ipo_transactions/", views.bulk_ipo_transactions, name="bulk_ipo_transactions"),
    path("bulk-transfer-transactions/", views.bulk_transfer_transactions, name="bulk_transfer_transactions"),
    path("api/transfer-batch/<uuid:batch_id>/", views.get_transfer_batch, name="get_transfer_batch"),
    path("api/transfer-group-ipos/<int:group_id>/", views.get_transfer_group_ipos, name="get_transfer_group_ipos"),
    path("api/get-group-dues/<int:group_id>/", views.get_group_dues, name="get_group_dues"),
    path('<int:IPOid>/get-all-groups/', views.get_all_groups, name='get_all_groups'),
    
    path('<str:IPOid>/send-status-telegram/', views.send_status_to_telegram, name='send_status_to_telegram'),
    path('<str:IPOid>/send-status-telegram-image/', views.send_status_to_telegram_image, name='send_status_to_telegram_image'),
    # path('delete-accounting-entries/', views.delete_accounting_entries, name='delete_accounting_entries'),
    # path('__debug__/', include('debug_toolbar.urls'))
    
    #PAN UPDATE URL
    path('generate-shared-link/', views.generate_shared_link, name='generate_shared_link'),
    path('access-link/<uuid:link_id>/', views.resolve_shared_link, name='resolve_shared_link'),
    path('access-link/<uuid:link_id>/<str:order_type>', views.resolve_shared_link, name='resolve_shared_link'),
    path('get-user-links/<int:IPOid>/<str:order_type>', views.get_user_links, name='get_user_links'),
    path('delete-link/', views.delete_link, name='delete_link'),
    path('update-link/<uuid:link_id>/', views.update_shared_link, name='update_shared_link'),
    path('send-link-mail/<uuid:linkId>/', views.send_link_mail, name='send_link_mail'),
    path('update-all-expiries/<int:IPOid>/', views.update_all_expiries, name='update_all_expiries'),
    path('send-all-link-mails/<int:IPOid>/', views.send_all_link_mails, name='send_all_link_mails'),
    path('bulk-generate-links/<str:IPOid>/', views.bulk_generate_links, name='bulk_generate_links'),
    path('update-link-status/', views.update_link_status, name='update_link_status'),
    
    #for multiple/bulk Order delete
    path('<str:IPOid>/BulkDeleteOrders/', views.BulkDeleteOrders, name='BulkDeleteOrders'),
    #for multiple/bulk Group delete button
    path('BulkDeleteGroup', views.BulkDeleteGroup, name='BulkDeleteGroup'),
    path('BulkDeleteIPO', views.BulkDeleteIPO, name='BulkDeleteIPO'),
    path('BulkDeleteClients', views.BulkDeleteClients, name='BulkDeleteClients'),
    path('generate-group-share-image/', views.generate_group_share_image, name='generate_group_share_image'),
]
