# Generated by Django 5.1.1 on 2025-10-17 12:21

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Expiry_Date',
            field=models.DateField(default=datetime.datetime(2026, 10, 17, 12, 21, 1, 856096, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('ipo_name', models.CharField(default=None, max_length=1000, null=True)),
                ('group_name', models.CharField(default=None, max_length=1000, null=True)),
                ('status', models.BooleanField(default=0)),
                ('remark', models.TextField(blank=True, null=True)),
                ('date_time', models.DateTimeField()),
                ('jv', models.BooleanField(default='False')),
                ('group', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='home.groupdetail')),
                ('ipo', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='home.currentiponame')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
