# Generated by Django 4.2.16 on 2026-01-22 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_customuser_expiry_date_accounting'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='remark',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Expiry_Date',
            field=models.DateField(default=datetime.datetime(2027, 1, 22, 11, 22, 51, 835536, tzinfo=datetime.timezone.utc)),
        ),
    ]
