# Generated by Django 4.2.13 on 2026-08-18 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_customuser_expiry_date_sharedlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Expiry_Date',
            field=models.DateField(default=datetime.datetime(2027, 8, 18, 10, 13, 30, 637794, tzinfo=datetime.timezone.utc)),
        ),
    ]
