# Generated by Django 4.2.13 on 2026-08-18 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_customuser_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Expiry_Date',
            field=models.DateField(default=datetime.datetime(2027, 8, 18, 10, 16, 9, 958250, tzinfo=datetime.timezone.utc)),
        ),
    ]
