# Generated by Django 4.2.13 on 2026-08-18 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_customuser_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Whatsapp_session',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Expiry_Date',
            field=models.DateField(default=datetime.datetime(2027, 8, 18, 11, 6, 46, 911711, tzinfo=datetime.timezone.utc)),
        ),
    ]
