# Generated by Django 4.2.13 on 2026-08-31 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_customuser_whatsapp_session_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Whatsapp_session',
        ),
        migrations.AddField(
            model_name='currentiponame',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Expiry_Date',
            field=models.DateField(default=datetime.datetime(2027, 8, 31, 12, 26, 39, 414091, tzinfo=datetime.timezone.utc)),
        ),
    ]
