# Generated by Django 4.2.13 on 2026-09-01 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_customuser_whatsapp_session_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentiponame',
            name='is_hidden',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Expiry_Date',
            field=models.DateField(default=datetime.datetime(2027, 9, 1, 6, 58, 33, 638137, tzinfo=datetime.timezone.utc)),
        ),
    ]
