# Generated by Django 4.2.16 on 2026-09-18 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_accounting_transfer_batch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Expiry_Date',
            field=models.DateField(default=datetime.datetime(2027, 9, 18, 5, 49, 23, 629208, tzinfo=datetime.timezone.utc)),
        ),
    ]
