# Generated by Django 4.2.13 on 2026-09-28 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_customuser_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Expiry_Date',
            field=models.DateField(default=datetime.datetime(2027, 9, 28, 10, 21, 28, 786361, tzinfo=datetime.timezone.utc)),
        ),
    ]
