# Generated by Django 4.2.13 on 2026-09-29 05:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_customuser_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Expiry_Date',
            field=models.DateField(default=datetime.datetime(2027, 9, 29, 5, 28, 48, 988556, tzinfo=datetime.timezone.utc)),
        ),
    ]
