# Generated by Django 4.2.16 on 2026-09-30 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_customuser_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Expiry_Date',
            field=models.DateField(default=datetime.datetime(2027, 9, 30, 10, 31, 47, 924944, tzinfo=datetime.timezone.utc)),
        ),
    ]
