"""
Django settings for userproject project.

Generated by 'django-admin startproject' using Django 3.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import pymysql

pymysql.version_info = (1, 4, 6, 'final', 0)
pymysql.install_as_MySQLdb()


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

os.environ["OMP_NUM_THREADS"] = "1"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '+w2t1e^5j(dc$6hp$z8q%j&u@()wo327xxiq@bd%z7*v27_hx%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# Allow all the hosts
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    # 'home.apps.HomeConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    'django_extensions',
    'rest_framework',
    'home',
    'pwa',
    'whatsapp.apps.WhatsAppConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'home.middleware.SessionExpiryMiddleware',
]

SESSION_COOKIE_AGE = 86400

SESSION_EXPIRE_AT_BROWSER_CLOSE = False

SESSION_ENGINE = 'django.contrib.sessions.backends.db'

ROOT_URLCONF = 'userproject.urls'

CSRF_TRUSTED_ORIGINS = [
    "https://ipoutility.in",
    "https://www.ipoutility.in",  # add this too if you use www
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'home.views.expiry_date_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'userproject.wsgi.application'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases


# Oci Database

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'ipoutility',
#         'USER': 'ipoutility',
#         'PASSWORD': 'Devam123321!',
#         'HOST': '141.148.204.115',  # Or your MySQL server's host address
#         'PORT': '3306',       # MySQL default port is 3306
#     }
# }

#Hostinger Database
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'IPOutility',
#         'USER': 'hostingerdb',
#         'PASSWORD': 'Hostingerdb@1234',
#         'HOST': '46.202.162.106',  # Or your MySQL server's host address
#         'PORT': '3306',       # MySQL default port is 3306
#     }
# }

DATABASES = {
    'default':{
        'ENGINE':'django.db.backends.sqlite3',
        'NAME':os.path.join(BASE_DIR,'db.sqlite3')
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = "/home/ubuntu/ipoutility-website/static/"
AUTH_USER_MODEL = "home.CustomUser"

STATIC_DIR = os.path.join(BASE_DIR, "static")
if os.path.normpath(STATIC_DIR) != os.path.normpath(STATIC_ROOT):
    STATICFILES_DIRS = [
        STATIC_DIR
    ]


# DATA_UPLOAD_MAX_MEMORY_SIZE = 2000485760
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000000

from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

PWA_APP_NAME = 'IPO Utility'
PWA_APP_DESCRIPTION = 'IPO Utility Web App'
PWA_APP_THEME_COLOR = '#686868'
PWA_APP_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
    {'src': '/static/image/pwa_icon_192.png', 'sizes': '192x192', 'purpose': 'any maskable'},
    {'src': '/static/image/pwa_icon_512.png', 'sizes': '512x512', 'purpose': 'any maskable'},
]
PWA_APP_ICONS_APPLE = [
    {'src': '/static/image/pwa_icon_192.png', 'sizes': '192x192'},
    {'src': '/static/image/pwa_icon_512.png', 'sizes': '512x512'},
]
PWA_APP_SPLASH_SCREEN = [
    {'src': '/static/image/pwa_icon_512.png', 'media': '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)'},
    {'src': '/static/image/pwa_icon_512.png', 'media': '(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2)'},
    {'src': '/static/image/pwa_icon_512.png', 'media': '(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2)'},
]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'en-US'

# Meta WhatsApp Cloud API configuration. Keep credentials in the environment.
# WHATSAPP_API_VERSION = os.environ.get('WHATSAPP_API_VERSION', 'v21.0')
# WHATSAPP_PHONE_NUMBER_ID = os.environ.get('WHATSAPP_PHONE_NUMBER_ID', '')
# WHATSAPP_ACCESS_TOKEN = os.environ.get('WHATSAPP_ACCESS_TOKEN')

WHATSAPP_API_VERSION = 'v21.0'
WHATSAPP_ACCESS_TOKEN = 'EAARwZCKnack4BSWdUyaMxAnN0EzBEXHYfBBUI2ZB2ZBF4oF6TBcLx4XetVTqMpIYGYyYuZBJ9VtkGZAQrWW5WcVPMVHbaioujlwwwfTl4mqZBOdcrxfiNhHhGBqZBQIuADCOS9VmNlCYFVDfsW7sZAQZC4NLOctBDAfLBt2ewcYCcnXIk6MFBIvyxU9G7OeQlcb9vHQZDZD'
WHATSAPP_PHONE_NUMBER_ID = '1287337667797572'
